//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.PostTags = new HashSet<PostTag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TagCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual User User { get; set; }
    }
}
