//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Categories = new HashSet<Category>();
            this.Media = new HashSet<Medium>();
            this.PostPraises = new HashSet<PostPrais>();
            this.Posts = new HashSet<Post>();
            this.PostTags = new HashSet<PostTag>();
            this.Tags = new HashSet<Tag>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string RegisterIp { get; set; }
        public string RegisterCity { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastLoginIp { get; set; }
        public string LastLoginCity { get; set; }
        public bool IsDeleted { get; set; }
        public string Mobile { get; set; }
        public bool MobileActivated { get; set; }
        public string Email { get; set; }
        public bool EmailActivated { get; set; }
        public int LoginErrorCount { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Medium> Media { get; set; }
        public virtual ICollection<PostPrais> PostPraises { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
